### ISSUE TITLE
[Bug]: convertTimeHHMM does not work

### ISSUE THREAD

**Issue by ronline23** [BagelBeef/ha-departureCard#12]
### What happend?

Setting „convertTimeHHMM: true“ leads to an undefined output on the dashboard:

**undefined is not an object (evaluating 'connection[config.connection_properties.departure].replace')**

Sensor output and Yaml provided below.

Any idea why this happens?

### What version of this custom-card are you using?

2025.1.4.

### What version of ha-db_infoscreen are you using?

2025.02.0

### Example YAML snippet

```yaml
type:%20custom%3Adeparture-card%0Atitle%3A%20Radtkestra%C3%9Fe%0Aentity%3A%20sensor.900049156_departures%0Aconnections_attribute%3A%20next_departures%0Adisplayed_connections%3A%204%0Aunix_time%3A%20false%0AconvertTimeHHMM%3A%20true%0Aconnection_properties%3A%0A%20%20targets%3A%20null%0A%20%20train%3A%20train%0A%20%20platform%3A%20platform%0A%20%20show_platform%3A%20false%0A%20%20departure%3A%20scheduledDeparture%0A%20%20delay%3A%20delayDeparture%0A%20%20isCancelled%3A%20isCancelled%0A%20%20stopAttribute%3A%20route%0A%20%20stationName%3A%20900049156%0A
```

### If you found anything in the log

```txt

```

### Context of departure entity

```json
next_departures:
  - delay: 0
    destination: U Fehrbelliner Platz
    direction: U Fehrbelliner Platz
    isCancelled: null
    messages: []
    platform: null
    scheduledPlatform: null
    scheduledTime: "2025-02-12 09:35:00"
    time: "2025-02-12 09:35:00"
    train: "115"
    trainNumber: "109622"
  - delay: 1
    destination: Düppel-Süd, Neuruppiner Str.
    direction: Düppel-Süd, Neuruppiner Str.
    isCancelled: null
    messages: []
    platform: null
    scheduledPlatform: null
    scheduledTime: "2025-02-12 09:41:00"
    time: "2025-02-12 09:42:00"
    train: "115"
    trainNumber: "109422"
  - delay: 0
    destination: U Fehrbelliner Platz
    direction: U Fehrbelliner Platz
    isCancelled: null
    messages: []
    platform: null
    scheduledPlatform: null
    scheduledTime: "2025-02-12 09:55:00"
    time: "2025-02-12 09:55:00"
    train: "115"
    trainNumber: "109623"
  - delay: 0
    destination: Düppel-Süd, Neuruppiner Str.
    direction: Düppel-Süd, Neuruppiner Str.
    isCancelled: null
    messages: []
    platform: null
    scheduledPlatform: null
    scheduledTime: "2025-02-12 10:01:00"
    time: "2025-02-12 10:01:00"
    train: "115"
    trainNumber: "109423"
station: "900049156"
via_stations: []
last_updated: "2025-02-12T09:28:05.327265"
attribution: Data provided by API https://dbf.finalrewind.org/900049156.json?hafas=VBB
icon: mdi:train
friendly_name: 900049156 Departures
```

**Comment by BagelBeef** [comment]
Hey,

your yaml configuration seems wrong. 

Your sensor provides the information for delay and time under different attribute names. 

**scheduledTime**: "2025-02-12 09:35:00"


Try:

departure: scheduledTime
delay: delay

Greetings from cologne

**Comment by BagelBeef** [comment]
I mean the YAML Code you use in your Dashboard for the card configuration.  

Sometimes the information given by the API behind ha-db-infoscreen differ from station to station. You used _hafas=VBB_ for this station. I guess the other station you set up uses another data source then VBB and provides the time and delay information with _scheduledDeparture_ and _delayDeparture_.


I tested it and can't see any problems:
<img width="508" alt="Image" src="https://github.com/user-attachments/assets/c1df3886-ed57-4798-b247-c4b06cfb7206" />

Try this in your Dashboard:

```
type: custom:departure-card
title: Radtkestraße
entity: sensor.900049156_departures
connections_attribute: next_departures
displayed_connections: 4
unix_time: false
convertTimeHHMM: true
connection_properties:
  targets: null
  train: train
  platform: platform
  show_platform: false
  departure: scheduledTime 
  delay: delay 
  isCancelled: isCancelled
  stopAttribute: route
  stationName: 900049156
```
