### ISSUE TITLE
Flickering Card Position

### ISSUE THREAD

**Issue by StefanDENord** [BagelBeef/ha-departureCard#15]
https://github.com/user-attachments/assets/d20d6236-c9ef-4f1f-84b0-d9ce3acd62d9

### What happend?

Hi,
i have added some formattation to the departure card. This results into flickering top and button borders with chaning the position of the departure card. How can i solve this problem?

Thanks!

`card_mod:
  style: |
    ha-card {
      border-radius: 0px 0px 0px 0px !important;
      border-width: 0px 1px 0px 1px;
      border-color: rgb(220,0,0);
      }
`

### What version of this custom-card are you using?

2025.1.4

### What version of ha-db_infoscreen are you using?

2025.02.3

### Example YAML snippet

```yaml
type: custom:departure-card
title: Kirchweyhe - Syke
entity: sensor.kirchweyhe_departures_via_syke
connections_attribute: next_departures
displayed_connections: 3
unix_time: false
convertTimeHHMM: false
connection_properties:
  targets: null
  train: train
  platform: platform
  show_platform: true
  departure: scheduledDeparture
  delay: delayDeparture
  isCancelled: isCancelled
  stopAttribute: route
  filterByStop: null
  stationName: Kirchweyhe
card_mod:
  style: |
    ha-card {
      border-radius: 0px 0px 0px 0px !important;
      border-width: 0px 1px 0px 1px;
      border-color: rgb(220,0,0);
      }
view_layout:
  column: 1
```

### If you found anything in the log

```txt

```

### Context of departure entity

```json

```
