### ISSUE TITLE
[Bug]: keine Anzeige im Dashboard

### ISSUE THREAD

**Issue by Toudi76** [BagelBeef/ha-departureCard#20]
### What happend?

Seit ein paar Tagen werden keine Werte mehr Angezeigt 

### What version of this custom-card are you using?

2025.3.2

### What version of ha-db_infoscreen are you using?

2025.03.0

### Example YAML snippet

type: custom:departure-card
            title: Pelzerstr.
            entity: sensor.pelzerstrasse_departures
            connections_attribute: next_departures
            displayed_connections: 8
            unix_time: false
            convertTimeHHMM: true
            connection_properties:
              targets: null
              train: line
              platform: platform
              show_platform: true
              departure: scheduledDeparture
              delay: null
              isCancelled: is_cancelled
              stopAttribute: null
              filterByStop: null
              stationName: null

```

### If you found anything in the log

```txt

```

### Context of departure entity

next_departures:
  - countdown: "1"
    datetime: 1741852500
    delay: null
    destination: Hamm, Werries Wendeplatz
    hints: []
    is_cancelled: 0
    line: "3"
    mot: "5"
    occupancy: null
    origin: Hamm, Pelkum Selbachpark
    platform: "1"
    platform_name: ""
    platform_type: null
    rt_datetime: null
    sched_datetime: 1741852500
    train_name: null
    train_no: null
    train_type: null
    type: StadtBus
    departure_current: "08:55:00"
    arrival_current: "08:55:00"

```

**Comment by BagelBeef** [comment]
I really need more information than this if you want me to help you. 

Yaml Dashboard configuration 
Content of your entity

**Comment by Toudi76** [comment]
Sorry , dashboard yaml
type: custom:departure-card
            title: Pelzerstr.
            entity: sensor.pelzerstrasse_departures
            connections_attribute: next_departures
            displayed_connections: 8
            unix_time: false
            convertTimeHHMM: true
            connection_properties:
              targets: null
              train: line
              platform: platform
              show_platform: true
              departure: scheduledDeparture
              delay: null
              isCancelled: is_cancelled
              stopAttribute: null
              filterByStop: null
              stationName: null

And content of Entity

**Comment by BagelBeef** [comment]
Du zeigst auf eine falsche Variable für die Abfahrtszeit. 
Im YAML nutzt du: scheduledDeparture
In der Entität stehen die Abfahrtszeiten aber in "sched_datetime". Die Zeiten stehen dort in UNIX-Time.
Unix_time muss also true sein. 

Das sollte klappen. 
```
type: custom:departure-card
title: Pelzerstr.
entity: sensor.pelzerstrasse_departures
connections_attribute: next_departures
displayed_connections: 8
unix_time: true
convertTimeHHMM: false
connection_properties:
  targets: null
  train: line
  platform: platform
  show_platform: true
  departure: sched_datetime
  delay: delay
  isCancelled: is_cancelled 

```

<img width="996" alt="Image" src="https://github.com/user-attachments/assets/2e6ca139-2f56-424a-8c6e-d7943caebc28" />
